const recipesData = {
const recipesData =   "breakfast": [
const recipesData =     {
const recipesData =       "id": 1,
const recipesData =       "name": "Нощни овесени ядки с ябълка и канела",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 2,
const recipesData =       "name": "Протеинов 'сандвич' с извара и краставица",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 3,
const recipesData =       "name": "Смути 'Зелена енергия'",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 4,
const recipesData =       "name": "Протеинова 'Бърканица' в чаша",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 5,
const recipesData =       "name": "Пълнозърнеста питка с тахан и банан",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 6,
const recipesData =       "name": "Извара с ядки и канела в буркан",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 7,
const recipesData =       "name": "Експресен 'Пудинг' с кисело мляко и чия",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 8,
const recipesData =       "name": "Хрупкава оризовка с пушена сьомга",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 9,
const recipesData =       "name": "Пълнозърнест тост с котидж сирене и репички",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 10,
const recipesData =       "name": "Авокадо 'лодка' с яйце",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 11,
const recipesData =       "name": "Кефир с конопено семе и горски плодове",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 12,
const recipesData =       "name": "'Сандвич' от ябълка с фъстъчено масло",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 13,
const recipesData =       "name": "Ролца от пуешко филе с хумус",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 14,
const recipesData =       "name": "Бързи бананови 'бисквити' с две съставки",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 15,
const recipesData =       "name": "Кокосов йогурт с тиквени семки",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 1,
const recipesData =       "name": "Топла вода с мед и пчелен прашец",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 2,
const recipesData =       "name": "Свеж айрян с щипка хималайска сол",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 3,
const recipesData =       "name": "Желе от кисело мляко с пресни плодове",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 4,
const recipesData =       "name": "Чай от джинджифил с резен лимон",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 5,
const recipesData =       "name": "Сурови тиквени семки и червени боровинки",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 6,
const recipesData =       "name": "Кокосова вода с чия и лайм",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 7,
const recipesData =       "name": "Оризовка с извара и кимион",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 8,
const recipesData =       "name": "Бульон от кости (Bone Broth) в чаша",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 9,
const recipesData =       "name": "Рендосана ябълка с канела",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 10,
const recipesData =       "name": "Зелено смути 'Чиста енергия'",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 11,
const recipesData =       "name": "Поширано яйце върху резен домат",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 12,
const recipesData =       "name": "Шепа орехи, накиснати от вечерта",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 13,
const recipesData =       "name": "Супена лъжица зехтин с лимон",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 14,
const recipesData =       "name": "Малка купичка мисо супа",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 15,
const recipesData =       "name": "Три лъжици кисело мляко с ленено семе",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 1,
const recipesData =       "name": "Омлет с овесени ядки и сирене",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 2,
const recipesData =       "name": "Елда с извара, ленено семе и орехи",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 3,
const recipesData =       "name": "Пълнозърнест хляб с телешко филе и горчица",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 4,
const recipesData =       "name": "Кисело мляко с тахан, коноп и суров мед",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 5,
const recipesData =       "name": "'Енергийна' киноа с яйце и авокадо",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 6,
const recipesData =       "name": "Протеинови палачинки с извара и банан",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 7,
const recipesData =       "name": "Багета от лимец със сьомга и крема сирене",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 8,
const recipesData =       "name": "Скир с мюсли от древни зърна и годжи бери",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 9,
const recipesData =       "name": "Тортила с черен боб, яйце и салца",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 10,
const recipesData =       "name": "'Атомно' смути с фъстъчено масло и овес",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 11,
const recipesData =       "name": "Солени гофрети от нахутено брашно",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 12,
const recipesData =       "name": "'Мусака' закуска с червена леща и спанак",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 13,
const recipesData =       "name": "Ръжено руло с пуешко и хумус",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 14,
const recipesData =       "name": "Протеинов 'Пудинг' с чия и извара",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 15,
const recipesData =       "name": "'Шакшука' с нахут и фета сирене",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 16,
const recipesData =       "name": "Запечена овесена каша с тиква и семена",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     }
const recipesData =   ],
const recipesData =   "lunch": [
const recipesData =     {
const recipesData =       "id": 1,
const recipesData =       "name": "Салата 'Жива енергия' в стъклен буркан",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 2,
const recipesData =       "name": "Ръжено руло с пуешко и авокадо",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 3,
const recipesData =       "name": "Средиземноморска купа с леща и запечени зеленчуци",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 4,
const recipesData =       "name": "Сьомгова пастърма с гарнитура от зелен боб",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 5,
const recipesData =       "name": "Протеинова кутия с яйца, сирене и ядки",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 6,
const recipesData =       "name": "Супа от червена леща с джинджифил и куркума",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 7,
const recipesData =       "name": "Салата с лимец, магданоз и козе сирене",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 8,
const recipesData =       "name": "Пилешки шишчета с розмарин и задушен карфиол",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 9,
const recipesData =       "name": "Постни сарми с кафяв ориз и орехи",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 10,
const recipesData =       "name": "Пълнена чушка с извара и белтъци",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 11,
const recipesData =       "name": "Кюфтенца от броколи и елда на фурна",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 12,
const recipesData =       "name": "Бърза салата с риба тон, боб и царевица",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 13,
const recipesData =       "name": "Телешко с нахут и пресен спанак",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 14,
const recipesData =       "name": "Риба 'en papillote' с тиквички и чери домати",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 15,
const recipesData =       "name": "'Фалшиво' ризото от киноа с гъби",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 16,
const recipesData =       "name": "Салата с пилешко, авокадо и нар",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 17,
const recipesData =       "name": "Киш без тесто с тиквички и яйца",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 18,
const recipesData =       "name": "'Буда боул' с нахут, батат и кейл",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     }
const recipesData =   ],
const recipesData =   "snack": [
const recipesData =     {
const recipesData =       "id": 1,
const recipesData =       "name": "'Енергийни хапки' с мака и сурово какао",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 2,
const recipesData =       "name": "Пудинг от чия и 'Златно мляко'",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 3,
const recipesData =       "name": "Едамаме с морска сол и чили нишки",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 4,
const recipesData =       "name": "'Кето' кокосови ленти с лайм",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 5,
const recipesData =       "name": "Солени крекери от ленено семе и розмарин",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 6,
const recipesData =       "name": "Трюфели от авокадо и шамфъстък",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 7,
const recipesData =       "name": "Темпе шишчета с фъстъчен дип",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 8,
const recipesData =       "name": "Печен нахут с пушен червен пипер",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 9,
const recipesData =       "name": "Кефирен шейк с боровинки и колаген",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 10,
const recipesData =       "name": "Краставичени 'суши' ролца с лабне",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 11,
const recipesData =       "name": "Пълнени фурми с орехов тахан и коноп",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 12,
const recipesData =       "name": "Мини палачинки от червена леща",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 13,
const recipesData =       "name": "Сорго 'пуканки' с хранителна мая",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 14,
const recipesData =       "name": "Мисо супа в чаша с тофу",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     },
const recipesData =     {
const recipesData =       "id": 15,
const recipesData =       "name": "Чия пудинг със сок от вишни (Sleepy Girl)",
const recipesData =       "why": "Метаболитна оптимизация чрез прецизна комбинация от макронутриенти.",
const recipesData =       "base": [],
const recipesData =       "boost": [],
const recipesData =       "instructions": [],
const recipesData =       "prep_time": "5-15 минути",
const recipesData =       "difficulty": "Лесна"
const recipesData =     }
const recipesData =   ]
const recipesData = };
